name: Scrape Details

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * *' # Runs everyday at 3 AM IST (21:30 UTC)
    - cron: '30 5 * * *'  # Runs everyday at 11 AM IST (05:30 UTC)
    - cron: '30 13 * * *' # Runs everyday at 7 PM IST (13:30 UTC)

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions for committing changes
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for proper commit/push

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run scrape_details.py
      run: python scrape_details.py

    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Automated update from scrape_details.py" || echo "No changes to commit"
        git push
